easy_admin:
    entities:
        Mahasiswa:
            class: App\Entity\Mahasiswa
            form:
                title: 'Add Mahasiswasss'
                # form_options: { validation_groups: ['Default'] }
